// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNM8xPsPorBQzPWVyopGGARK8bGD79Vg',
    appId: '1:332133720683:web:f4c7541fa86594c307872e',
    messagingSenderId: '332133720683',
    projectId: 'nakilaa-1606c',
    authDomain: 'nakilaa-1606c.firebaseapp.com',
    databaseURL: 'https://nakilaa-1606c-default-rtdb.firebaseio.com',
    storageBucket: 'nakilaa-1606c.firebasestorage.app',
    measurementId: 'G-664SJXWRLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzM5tTb2UdCu-WmXZEkc5X0RqxVD2YFWk',
    appId: '1:332133720683:android:2c9fb7b3d6f3e35507872e',
    messagingSenderId: '332133720683',
    projectId: 'nakilaa-1606c',
    databaseURL: 'https://nakilaa-1606c-default-rtdb.firebaseio.com',
    storageBucket: 'nakilaa-1606c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPiWCK7IEYqj436KIAEh2k78BNdyDjMc0',
    appId: '1:332133720683:ios:9e8c65820ee2238607872e',
    messagingSenderId: '332133720683',
    projectId: 'nakilaa-1606c',
    databaseURL: 'https://nakilaa-1606c-default-rtdb.firebaseio.com',
    storageBucket: 'nakilaa-1606c.firebasestorage.app',
    iosClientId: '332133720683-cc38k1qautb1flcqnhqm0emd33ukh5hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.nakila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPiWCK7IEYqj436KIAEh2k78BNdyDjMc0',
    appId: '1:332133720683:ios:9e8c65820ee2238607872e',
    messagingSenderId: '332133720683',
    projectId: 'nakilaa-1606c',
    databaseURL: 'https://nakilaa-1606c-default-rtdb.firebaseio.com',
    storageBucket: 'nakilaa-1606c.firebasestorage.app',
    iosClientId: '332133720683-cc38k1qautb1flcqnhqm0emd33ukh5hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.nakila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuNM8xPsPorBQzPWVyopGGARK8bGD79Vg',
    appId: '1:332133720683:web:859201d5549ccf9207872e',
    messagingSenderId: '332133720683',
    projectId: 'nakilaa-1606c',
    authDomain: 'nakilaa-1606c.firebaseapp.com',
    databaseURL: 'https://nakilaa-1606c-default-rtdb.firebaseio.com',
    storageBucket: 'nakilaa-1606c.firebasestorage.app',
    measurementId: 'G-CMTKCQ58WS',
  );
}
